apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: kafka
    component: kafka-zoo
  name: kafka-zoo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
        component: kafka-zoo
    spec:
      containers:
      - name: zoo
        image: confluent/zookeeper
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: kafka-zoo-svc
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-zoo-svc
  labels:
    app: kafka
    component: kafka-zoo
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  selector:
    app: kafka
    component: kafka-zoo